server:
  port: 8081

spring:
  profile: dev
  config:
    import: optional:file:.env[.properties]
  application:
    name: TodoApp
    api:
      base-url: ${API_BASE_URL}
#  mail:
#    host: ${MAIL_HOST}
#    port: ${MAIL_PORT}
#    username: ${MAIL_USER}
#    password: ${MAIL_PASS}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
  datasource:
    url: jdbc:mysql://localhost:3306/todo
    username: omkar
    password: omkar
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
logging:
  level:
    com:
      myapp: DEBUG
    org:
      springframework: INFO
management:
  endpoints:
    web:
      exposure:
        include: "*"
    base-path: /actuator
  endpoint:
    prometheus:
      enabled: true
