server:
  port: ${SERVER_PORT}
  address: ${SERVER_ADDRESS}

spring:
  profile: prod
  application:
    name: TodoApp
    api:
      base-url: ${API_BASE_URL}
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
logging:
  level:
    com:
      myapp: DEBUG
    org:
      springframework: INFO