
server:
  port: ${SERVER_PORT}
  address: ${SERVER_ADDRESS}

spring:
  profile: prod
  application:
    name: TodoApp
    api:
      base-url:  ${API_BASE_URL}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
logging:
  level:
    com:
      myapp: DEBUG
    org:
      springframework: INFO
management:
  endpoints:
    web:
      exposure:
        include: "*"
    base-path: /actuator
  endpoint:
    prometheus:
      enabled: true
