server:
  port: ${SERVER_PORT:8081}

spring:
  profiles:
    active: dev
  application:
    name: TodoApp

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:todo}
    username: ${DB_USER:omkar}
    password: ${DB_PASS:omkar}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  thymeleaf:
    cache: false

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          debug: false

logging:
  level:
    com:
      myapp: DEBUG
    org:
      springframework: trace

management:
  endpoints:
    web:
      exposure:
        include: '*'
    base-path: /actuator
  endpoint:
    prometheus:
      enabled: true
