pipeline {
    agent any

    tools {
        maven 'Maven_3.9.10'
    }

    environment {
        SPRING_PROFILE = 'prod'
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'git@github.com:theomkardeshpande/ToDo_ListApp.git',
                    credentialsId: 'github-credentials'
            }
        }

        stage('Build & Test') {
            steps {
                sh 'mvn clean package'
                sh 'mvn test'
            }
        }

        stage('Deploy') {
          steps {
            withCredentials([usernamePassword(credentialsId: 'db-credentials',
                                              usernameVariable: 'DB_USER',
                                              passwordVariable: 'DB_PASS')]) {
              sh '''
                echo "Launching Spring Boot App against MySQL..."
                java -jar target/app.jar \
                  --spring.datasource.username=$DB_USER \
                  --spring.datasource.password=$DB_PASS \
                  --spring.datasource.url=jdbc:mysql://mysql_db:3306/todo
              '''
            }
          }
}
    }

    post {
        success {
            echo 'Build and deployment succeeded!'
        }
        failure {
            echo 'Build failed. Check logs for details.'
        }
    }
}